"use client";

import { Typography, Box, Button } from "@mui/material"; // import mui components

export default function Home() {
  return (
    // box is a mui component similar to div
    <Box
      sx={{
        maxWidth: 600,
        margin: "auto",
        padding: 4,
        textAlign: "center",
        backgroundColor: "background.paper",
        borderRadius: 2,
        boxShadow: 3,
      }}
    >
      <Typography variant="h3" component="h1" gutterBottom color="primary">
        Welcome to the Salamander Video Tracker Home Page
      </Typography>

      <Typography variant="body1" color="text.secondary" sx={{ mt: 2 }}>
        You can process videos or track job statuses/download their csv files.
      </Typography>

      <Box sx={{ mt: 4, display: "flex", justifyContent: "center", gap: 2 }}>
        <Button variant="contained" color="primary" href="/videos">
          Go to Salamander Videos
        </Button>
        <Button variant="outlined" color="secondary" href="/jobs">
          View Job Statuses/CSV Links
        </Button>
      </Box>

      <Box sx={{ mt: 4 }}>
        <img
          src="/SalamanderTransparent.png"
          alt="Cute Salamander generated by AI"
          style={{
            maxWidth: "100%",
            height: "300px",
            borderRadius: "8px",
          }}
        />
      </Box>
    </Box>
  );
}
